### ISSUE TITLE
카페 '좋아요' 기능 구현

### ISSUE THREAD

**Issue by mycookie1** [Chilled-Run/ChilledCafe#15]
### 문제 상황
- 추천기능을 위해서 '좋아요'가 필요함

### TODO
- [x] 디테일 페이지에 '좋아요' 기능 추가
- [x] 카페리스트 페이지에서 '좋아요'를 볼 수 있게 추가
- [x] 카페 struct, 서버 데이터에 좋아요 추가
