### ISSUE TITLE
FirebaseStore에서 이미지 불러오기

### ISSUE THREAD

**Issue by mycookie1** [Chilled-Run/ChilledCafe#32]
### 문제 상황
- FirebaseStore에서 이미지를 가져오지 않아 사용할 수 없는 이미지가 있었다.

### TODO
- [x] FirebaseStore 데이터 변경
- [x] FirebaseStore에서 url 받아오기
- [x] 이미지 그리는 함수만들기
