### ISSUE TITLE
지역에 따른 카페 불러오기

### ISSUE THREAD

**Issue by mycookie1** [Chilled-Run/ChilledCafe#7]
### 문제 상황
- 메인 페이지에서 지역을 선택하면 카페 정보를 받아와야한다.

### TODO
- [x] 카페 구조 만들기
- [x] 서버를 통해 카페 정보 받아오기
- [x] dictionary 형태로 가공
